name: Fuzz Parser

on:
  push:
    branches: [master]
    paths:
      - src/scanner.c
  pull_request:
    paths:
      - src/scanner.c

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Install pinned tree-sitter CLI
        run: |-
          npm ci --legacy-peer-deps --ignore-scripts
          npm rebuild tree-sitter-cli
      - name: Run fuzzer
        run: npx tree-sitter fuzz --iterations 100
